// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: data_type.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataType int32

const (
	DataType_DATATYPE_UNKNOWN DataType = 0
	DataType_CHAR             DataType = 1
	DataType_INT8             DataType = 2
	DataType_INT16            DataType = 3
	DataType_INT32            DataType = 4
	DataType_INT64            DataType = 5
	DataType_UINT8            DataType = 6
	DataType_UINT16           DataType = 7
	DataType_UINT32           DataType = 8
	DataType_UINT64           DataType = 9
	DataType_FLOAT            DataType = 10
	DataType_DOUBLE           DataType = 11
	DataType_OTHER            DataType = 12
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0:  "DATATYPE_UNKNOWN",
		1:  "CHAR",
		2:  "INT8",
		3:  "INT16",
		4:  "INT32",
		5:  "INT64",
		6:  "UINT8",
		7:  "UINT16",
		8:  "UINT32",
		9:  "UINT64",
		10: "FLOAT",
		11: "DOUBLE",
		12: "OTHER",
	}
	DataType_value = map[string]int32{
		"DATATYPE_UNKNOWN": 0,
		"CHAR":             1,
		"INT8":             2,
		"INT16":            3,
		"INT32":            4,
		"INT64":            5,
		"UINT8":            6,
		"UINT16":           7,
		"UINT32":           8,
		"UINT64":           9,
		"FLOAT":            10,
		"DOUBLE":           11,
		"OTHER":            12,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_data_type_proto_enumTypes[0].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_data_type_proto_enumTypes[0]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_data_type_proto_rawDescGZIP(), []int{0}
}

var File_data_type_proto protoreflect.FileDescriptor

var file_data_type_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2a, 0xa6, 0x01, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14,
	0x0a, 0x10, 0x44, 0x41, 0x54, 0x41, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f,
	0x57, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x43, 0x48, 0x41, 0x52, 0x10, 0x01, 0x12, 0x08,
	0x0a, 0x04, 0x49, 0x4e, 0x54, 0x38, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x4e, 0x54, 0x31,
	0x36, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x4e, 0x54, 0x33, 0x32, 0x10, 0x04, 0x12, 0x09,
	0x0a, 0x05, 0x49, 0x4e, 0x54, 0x36, 0x34, 0x10, 0x05, 0x12, 0x09, 0x0a, 0x05, 0x55, 0x49, 0x4e,
	0x54, 0x38, 0x10, 0x06, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x49, 0x4e, 0x54, 0x31, 0x36, 0x10, 0x07,
	0x12, 0x0a, 0x0a, 0x06, 0x55, 0x49, 0x4e, 0x54, 0x33, 0x32, 0x10, 0x08, 0x12, 0x0a, 0x0a, 0x06,
	0x55, 0x49, 0x4e, 0x54, 0x36, 0x34, 0x10, 0x09, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x4c, 0x4f, 0x41,
	0x54, 0x10, 0x0a, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x4f, 0x55, 0x42, 0x4c, 0x45, 0x10, 0x0b, 0x12,
	0x09, 0x0a, 0x05, 0x4f, 0x54, 0x48, 0x45, 0x52, 0x10, 0x0c, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65, 0x63, 0x73, 0x79, 0x73, 0x2d,
	0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f, 0x70, 0x73, 0x2d, 0x6c, 0x69, 0x74, 0x65, 0x2f, 0x61, 0x70,
	0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_data_type_proto_rawDescOnce sync.Once
	file_data_type_proto_rawDescData = file_data_type_proto_rawDesc
)

func file_data_type_proto_rawDescGZIP() []byte {
	file_data_type_proto_rawDescOnce.Do(func() {
		file_data_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_data_type_proto_rawDescData)
	})
	return file_data_type_proto_rawDescData
}

var file_data_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_data_type_proto_goTypes = []interface{}{
	(DataType)(0), // 0: DataType
}
var file_data_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_data_type_proto_init() }
func file_data_type_proto_init() {
	if File_data_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_data_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_type_proto_goTypes,
		DependencyIndexes: file_data_type_proto_depIdxs,
		EnumInfos:         file_data_type_proto_enumTypes,
	}.Build()
	File_data_type_proto = out.File
	file_data_type_proto_rawDesc = nil
	file_data_type_proto_goTypes = nil
	file_data_type_proto_depIdxs = nil
}
